tag @e[hasitem={item=dragonmounts:aether_dragonscale_helmet,location=slot.armor.head}] add aether_1
tag @e[hasitem={item=dragonmounts:aether_dragonscale_chestplate,location=slot.armor.chest}] add aether_2
tag @e[hasitem={item=dragonmounts:aether_dragonscale_leggings,location=slot.armor.legs}] add aether_3
tag @e[hasitem={item=dragonmounts:aether_dragonscale_boots,location=slot.armor.feet}] add aether_4
tag @e[hasitem={item=dragonmounts:enchant_dragonscale_helmet,location=slot.armor.head}] add enchant_1
tag @e[hasitem={item=dragonmounts:enchant_dragonscale_chestplate,location=slot.armor.chest}] add enchant_2
tag @e[hasitem={item=dragonmounts:enchant_dragonscale_leggings,location=slot.armor.legs}] add enchant_3
tag @e[hasitem={item=dragonmounts:enchant_dragonscale_boots,location=slot.armor.feet}] add enchant_4
tag @e[hasitem={item=dragonmounts:ender_dragonscale_helmet,location=slot.armor.head}] add ender_1
tag @e[hasitem={item=dragonmounts:ender_dragonscale_chestplate,location=slot.armor.chest}] add ender_2
tag @e[hasitem={item=dragonmounts:ender_dragonscale_leggings,location=slot.armor.legs}] add ender_3
tag @e[hasitem={item=dragonmounts:ender_dragonscale_boots,location=slot.armor.feet}] add ender_4
tag @e[hasitem={item=dragonmounts:fire_dragonscale_helmet,location=slot.armor.head}] add fire_1
tag @e[hasitem={item=dragonmounts:fire_dragonscale_chestplate,location=slot.armor.chest}] add fire_2
tag @e[hasitem={item=dragonmounts:fire_dragonscale_leggings,location=slot.armor.legs}] add fire_3
tag @e[hasitem={item=dragonmounts:fire_dragonscale_boots,location=slot.armor.feet}] add fire_4
tag @e[hasitem={item=dragonmounts:forest_dragonscale_helmet,location=slot.armor.head}] add forest_1
tag @e[hasitem={item=dragonmounts:forest_dragonscale_chestplate,location=slot.armor.chest}] add forest_2
tag @e[hasitem={item=dragonmounts:forest_dragonscale_leggings,location=slot.armor.legs}] add forest_3
tag @e[hasitem={item=dragonmounts:forest_dragonscale_boots,location=slot.armor.feet}] add forest_4
tag @e[hasitem={item=dragonmounts:ice_dragonscale_helmet,location=slot.armor.head}] add ice_1
tag @e[hasitem={item=dragonmounts:ice_dragonscale_chestplate,location=slot.armor.chest}] add ice_2
tag @e[hasitem={item=dragonmounts:ice_dragonscale_leggings,location=slot.armor.legs}] add ice_3
tag @e[hasitem={item=dragonmounts:ice_dragonscale_boots,location=slot.armor.feet}] add ice_4
tag @e[hasitem={item=dragonmounts:moonlight_dragonscale_helmet,location=slot.armor.head}] add moonlight_1
tag @e[hasitem={item=dragonmounts:moonlight_dragonscale_chestplate,location=slot.armor.chest}] add moonlight_2
tag @e[hasitem={item=dragonmounts:moonlight_dragonscale_leggings,location=slot.armor.legs}] add moonlight_3
tag @e[hasitem={item=dragonmounts:moonlight_dragonscale_boots,location=slot.armor.feet}] add moonlight_4
tag @e[hasitem={item=dragonmounts:nether_dragonscale_helmet,location=slot.armor.head}] add nether_1
tag @e[hasitem={item=dragonmounts:nether_dragonscale_chestplate,location=slot.armor.chest}] add nether_2
tag @e[hasitem={item=dragonmounts:nether_dragonscale_leggings,location=slot.armor.legs}] add nether_3
tag @e[hasitem={item=dragonmounts:nether_dragonscale_boots,location=slot.armor.feet}] add nether_4
tag @e[hasitem={item=dragonmounts:sculk_dragonscale_helmet,location=slot.armor.head}] add sculk_1
tag @e[hasitem={item=dragonmounts:sculk_dragonscale_chestplate,location=slot.armor.chest}] add sculk_2
tag @e[hasitem={item=dragonmounts:sculk_dragonscale_leggings,location=slot.armor.legs}] add sculk_3
tag @e[hasitem={item=dragonmounts:sculk_dragonscale_boots,location=slot.armor.feet}] add sculk_4
tag @e[hasitem={item=dragonmounts:storm_dragonscale_helmet,location=slot.armor.head}] add storm_1
tag @e[hasitem={item=dragonmounts:storm_dragonscale_chestplate,location=slot.armor.chest}] add storm_2
tag @e[hasitem={item=dragonmounts:storm_dragonscale_leggings,location=slot.armor.legs}] add storm_3
tag @e[hasitem={item=dragonmounts:storm_dragonscale_boots,location=slot.armor.feet}] add storm_4
tag @e[hasitem={item=dragonmounts:sunlight_dragonscale_helmet,location=slot.armor.head}] add sunlight_1
tag @e[hasitem={item=dragonmounts:sunlight_dragonscale_chestplate,location=slot.armor.chest}] add sunlight_2
tag @e[hasitem={item=dragonmounts:sunlight_dragonscale_leggings,location=slot.armor.legs}] add sunlight_3
tag @e[hasitem={item=dragonmounts:sunlight_dragonscale_boots,location=slot.armor.feet}] add sunlight_4
tag @e[hasitem={item=dragonmounts:terra_dragonscale_helmet,location=slot.armor.head}] add terra_1
tag @e[hasitem={item=dragonmounts:terra_dragonscale_chestplate,location=slot.armor.chest}] add terra_2
tag @e[hasitem={item=dragonmounts:terra_dragonscale_leggings,location=slot.armor.legs}] add terra_3
tag @e[hasitem={item=dragonmounts:terra_dragonscale_boots,location=slot.armor.feet}] add terra_4
tag @e[hasitem={item=dragonmounts:water_dragonscale_helmet,location=slot.armor.head}] add water_1
tag @e[hasitem={item=dragonmounts:water_dragonscale_chestplate,location=slot.armor.chest}] add water_2
tag @e[hasitem={item=dragonmounts:water_dragonscale_leggings,location=slot.armor.legs}] add water_3
tag @e[hasitem={item=dragonmounts:water_dragonscale_boots,location=slot.armor.feet}] add water_4
tag @e[hasitem={item=dragonmounts:zombie_dragonscale_helmet,location=slot.armor.head}] add zombie_1
tag @e[hasitem={item=dragonmounts:zombie_dragonscale_chestplate,location=slot.armor.chest}] add zombie_2
tag @e[hasitem={item=dragonmounts:zombie_dragonscale_leggings,location=slot.armor.legs}] add zombie_3
tag @e[hasitem={item=dragonmounts:zombie_dragonscale_boots,location=slot.armor.feet}] add zombie_4